### PR TITLE
Migrating to Swift 4.2 using Xcode 10.

### PR DESCRIPTION
**Pull request by thisisjak**
#Supporting Swift4.2 and Xcode 10.

### CODE REVIEW

**Comment by thisisjak** [comment]
@JamesRGM @hoseking Can you please accept this Pull Request to add support for Swift4.2 and Xcode 10.

**Comment by thisisjak** [comment]
and create a new Release?

**Comment by thisisjak** [comment]
@JamesRGM @hoseking We need to migrate it to Swift5.1 and Xcode11 soon. Are you planning to do it?

**Comment by JamesRGM** [comment]
Hey @thisisjak somehow this completely flew under my radar. Very very sorry 🙇

**Pull request merged**
